name: Build AGS Shell

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      
    - name: Clone AGS repository
      run: |
        git clone https://github.com/Aylur/ags.git ags-repo
        
    - name: Clone Astal repository
      run: |
        git clone https://github.com/Aylur/astal.git astal-repo
        
    - name: Clone GTK4 layer shell repository
      run: |
        git clone https://github.com/wmww/gtk4-layer-shell.git gtk4-layer-shell-repo
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          npm \
          meson \
          ninja-build \
          golang-go \
          valac \
          valadoc \
          gobject-introspection \
          libgirepository1.0-dev \
          libgtk-3-dev \
          libgtk-layer-shell-dev \
          libgtk-4-dev \
          libwayland-dev \
          wayland-protocols \
          gtk-doc-tools \
          python3 \
          gjs \
          sass \
          build-essential \
          pkg-config
          
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Build and install GTK4 layer shell
      run: |
        cd gtk4-layer-shell-repo
        meson setup build
        ninja -C build
        sudo ninja -C build install
        sudo ldconfig
        
    - name: Install Astal dependencies
      run: |
        cd astal-repo/lib/astal/io
        meson setup build
        sudo meson install -C build
        
        cd ../gtk3
        meson setup build
        sudo meson install -C build
        
        cd ../gtk4
        meson setup build
        sudo meson install -C build
        
    - name: Install AGS dependencies
      run: |
        cd ags-repo
        npm install
        
    - name: Build and install AGS
      run: |
        cd ags-repo
        meson setup build
        sudo meson install -C build
        
    - name: Build AGS Shell
      run: |
        ags bundle app.ts ags-shell --gtk 4
        
    - name: Upload AGS Shell artifact
      uses: actions/upload-artifact@v4
      with:
        name: ags-shell
        path: ags-shell
        retention-days: 30
        
    - name: Create Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: softprops/action-gh-release@v1
      with:
        files: ags-shell
        tag_name: ags-shell-${{ github.run_number }}
        name: AGS Shell Build ${{ github.run_number }}
        body: |
          Automated build of AGS Shell
          
          - Commit: ${{ github.sha }}
          - Workflow: ${{ github.workflow }}
          - Run: ${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
